### PR TITLE
Fix sample selection to not always use first index

### LINKED ISSUE #52: go-torch with memory profiles always uses alloc_objects
We're always using the first field of the raw pprof output, which since 1.8 always includes inuse and alloc:
```
$ go tool pprof -raw zap.test prof.mem | head
PeriodType: space bytes
Period: 524288
Time: 2017-01-11 15:19:52.794622795 -0800 PST
Samples:
alloc_objects/count alloc_space/bytes inuse_objects/count inuse_space/bytes
        372     524992          0          0: 1 2 3 4 5 6 7 8 9 10 11
        372     524992          0          0: 1 2 12 13 14 6 7 8 9 10 11
      10923     524312          0          0: 15 16 4 5 6 7 8 9 10 11
    2982024  143137176          0          0: 17 18 19 20 21 22 23 24 25 26 27 28 29 30 6 7 8 9 10 11
       1491    2099969          0          0: 1 2 3 31 6 7 8 9 10 11
```

```
$ go tool pprof -raw -seconds 30 -alloc_objects zap.test prof.mem | head
PeriodType: space bytes
Period: 524288
Time: 2017-01-11 15:19:52.794622795 -0800 PST
Samples:
alloc_objects/count alloc_space/bytes inuse_objects/count inuse_space/bytes
        372     524992          0          0: 1 2 3 4 5 6 7 8 9 10 11
        372     524992          0          0: 1 2 12 13 14 6 7 8 9 10 11
      10923     524312          0          0: 15 16 4 5 6 7 8 9 10 11
````

go-torch should select the correct sample. The arguments that pprof supports are:
```
Sample value selection option (by index):
  -sample_index      Index of sample value to display
  -mean              Average sample value over first value
Sample value selection option (for heap profiles):
  -inuse_space      Display in-use memory size
  -inuse_objects    Display in-use object counts
  -alloc_space      Display allocated memory size
  -alloc_objects    Display allocated object counts
Sample value selection option (for contention profiles):
  -total_delay      Display total delay at each region
  -contentions      Display number of delays at each region
  -mean_delay       Display mean delay at each region
```

We should at least support the sample selection options.

### PR DESCRIPTION
**Pull request by prashantv**
Currently, go-torch always uses the first sample it finds in the
profile. With 1.8, memory profiles always have inuse/alloc so we
need to select the right sample, otherwise we're always showing
alloc.

This allows allows selection of a custom sample using sample_index
for non-memory profiles.

Fixes #52.

### CODE REVIEW

**Comment by prashantv** [comment]
The `glide.yaml` needed to be updated (to include the `require` subpackage), and to get that picked up in `glide.lock`, I had to regenerate the whole file. Really wish it was possible to just touch a single dependency!

File: pprof/select_sample.go [hunk 1]
```diff
@@ -0,0 +1,74 @@
+// Copyright (c) 2015 Uber Technologies, Inc.
```
Comment (sectioneight) [inline pprof/select_sample.go]: 2015?

File: pprof/parser_test.go [hunk 2]
```diff
@@ -172,7 +191,7 @@ func TestParseSampleCountMismatch(t *testing.T) {
 `
 	_, err := ParseRaw([]byte(contents))
 	require.Error(t, err, "Expected parseRaw to fail with sample count mismatch")
```
Comment (sectioneight) [inline pprof/parser_test.go]: Interesting, looks like the project was already using require?

Comment (prashantv) [inline pprof/parser_test.go]: yeah, it was just missing from the glide.yaml

File: pprof/select_sample.go (hunk 1 above)
Comment (prashantv) [inline pprof/select_sample.go]: Fixed
